config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "search" => "searches#search"
  get "search_book" => "books#search_book"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  scope :latest, -> { order(updated_at: :desc)}
  scope :rated, -> { order(rate: :desc) }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)

    if search == 'perfect_match'
      Book.where(title: word)
    elsif search == 'forward_match'
      Book.where('title LIKE ? OR body LIKE ?', "#{word}%", "#{word}%")
    elsif search == 'backward_match'
      Book.where('title LIKE ? OR body LIKE ?', "%#{word}", "%#{word}")
    else
      Book.where('title LIKE ? OR body LIKE ?', "%#{word}%", "%#{word}%")
    end
  end

  # def self.search_book(search_word)
  #   Book.where('category LIKE ?', "#{search_word}")
  # end
  def self.search_book(search_word)
    Tag.where('name LIKE ?', "#{search_word}")
  end  
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete(Tag.find_by(name: old))
    end

    new_tags.each do |new|
      new_book_tag = Tag.find_or_create_by(name: new)
      self.tags << new_book_tag
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_tags = @book.tags
  end

  def index
    if params[:sort_updated]
      @books = Book.latest
    elsif params[:high_rated]
      @books = Book.rated
    else
      @books = Book.all
    end
      @book = Book.new
      @tag_list = Tag.all
  end

  def create
    @book = current_user.books.new(book_params)
    @tag_list = params[:book][:name].split(',')
    if @book.save
      @book.save_tag(@tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    @tag_list = @book.tags.pluck(:name).join(', ')
    unless @user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    tag_list = params[:book][:name].split(',')
    if @book.update(book_params)
      old_relations = BookTag.where(book_id: @book.id)
      old_relations.each do |relation|
        relation.delete
      end
      @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  def search_book
    # @books = Book.search_book(params[:keyword])
    # @books = Book.tags.search_book(params[:keyword])
    @books = Book.tags
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_rate.html.erb
<div id="star-rate_<%= book.id %>" class="form-group"></div>
<script>
  $(document).bind('turbolinks:load ajax:complete', function() {
  $('#star-rate_<%= book.id %>').empty();
  $('#star-rate_<%= book.id %>').raty({
    size      : 20,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: <%= book.rate %>,
    });
  })
</script>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <!-- <div class="form-group">-->
  <!--  <#%= f.label :category %>-->
  <!--  <#%= f.text_field :category, class: 'form-control book_body' %>-->
  <!--</div>-->
  <div class="form-group">
    <%= f.label :name, 'Category' %>
    <%= f.text_field :name, value: @tag_list, class: 'form-control book_body' %>
  </div>
  
  <% if book.id == nil %>
    <div class="field" id="star">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        $('#star').empty();
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          scoreName: 'book[rate]',
        });
      })
    </script>
  <% else %>
    <%= render 'books/book_rate', book: book %>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
<% if false %>
<!--コメントアウト-->
        <% if book.category == nil %>
          <td></td>
        <% else %>
          <% if request.path.include?("users")%>
            <td><%= book.category %></td>
          <% else %>
            <td><%= link_to book.category, search_book_path(keyword: book.category), remote: true %></td>
          <% end %>
        <% end %>
<% end %>
        <% if book.tags == nil %>
          <td></td>
        <% else %>
          <% if request.path.include?("users")%>
            <td><%= book.tags.map(&:name).join(', ') %></td>
          <% else %>
            <% book.tags.each do |tag| %>
              <td><%= link_to tag.name, search_book_path(tag_id: tag.id) %></td>
            <% end %>
          <% end %>
        <% end %>
        <td class="favorite_btn_<%= book.id %>">
          <%= render 'favorites/favorite_btn', book: book %>
        </td>
        <td>コメント数: <%= book.book_comments.count %></td>
        <td><%= render 'books/book_rate', book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search_book.html.erb
<%= form_with url: search_book_path(keyword: book.category), method: :get, local: false do |f| %>
  <%= f.text_field :keyword %>
  <%= f.submit %>
<% end %>

app/views/books/books_latest.js.erb
$('#books_sort').html("<%= j(render 'index', books: @books) %>")

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'search_book', book: @book %>
      <%= link_to '新しい順', books_path(sort_updated: true), remote: true %>
      <span> ｜ </span>
      <%= link_to '評価の高い順', books_path(high_rated: true), remote: true %>
      <div id="books_sort">
        <%= render 'index', books: @books %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.js.erb
$('#books_sort').html("<%= j(render 'index', books: @books) %>")

app/views/books/search_book.html.erb
<!--$('#books_sort').html("<%#= j(render 'books/index', books: @books) %>");-->
<!--$('#keyword').val('');-->

<p><%= @books.map(&:name).join(', ') %></p>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <!--<td><%#= @book.category %></td>-->
          <td><%= @book.tags.map(&:name).join(', ') %></td>
          <td class="favorite_btn_<%= @book.id %>">
            <%= render 'favorites/favorite_btn', book: @book %>
          </td>
          <td>コメント数: <%= @book.book_comments.count %></td>
          <td><%= render 'book_rate', book: @book %></td>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <table id="book_comments">
        <%= render 'book_comments/book_comments', book: @book %>
      </table>
      <div id="comment_form">
        <%= render 'book_comments/comment_form', book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>